CREATE TABLE "componentes" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "modelo_id" BIGINT NOT NULL,
    "tipo" VARCHAR(15) NOT NULL,
    "numero_serie" VARCHAR(80) NOT NULL,
    "fabricacion_mes" DATE,
    "observaciones" TEXT,
    CONSTRAINT "componentes_modelo_id_numero_serie_key" UNIQUE ("modelo_id", "numero_serie"),
    CONSTRAINT "componentes_id_tipo_key" UNIQUE ("id", "tipo"),
    CONSTRAINT "componentes_modelo_id_tipo_fkey" FOREIGN KEY ("modelo_id", "tipo")
        REFERENCES "modelos_componentes" ("id", "tipo") ON UPDATE RESTRICT ON DELETE RESTRICT,
    CONSTRAINT "componentes_serie_normalizada" CHECK (
        length("numero_serie") > 0 AND
        "numero_serie" = upper(regexp_replace("numero_serie", '[.[:space:]-]', '', 'g'))
    ),
    CONSTRAINT "componentes_fabricacion_mes" CHECK (
        "fabricacion_mes" IS NULL OR EXTRACT(DAY FROM "fabricacion_mes") = 1
    )
);
